[package]
name = "polypomo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
ctrlc = "3.2.5"
interprocess = "1.2.1"
pausable_clock = "1.0.1"
